server {
    listen 443 ssl;
    server_name corsproxy.budabit.club;

    ssl_certificate /etc/letsencrypt/live/corsproxy.budabit.club/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/corsproxy.budabit.club/privkey.pem;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        proxy_pass http://corsproxy:8080;
    }
}

server {
    listen 80;
    server_name corsproxy.budabit.club;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
